version: '3.8'

volumes:
  postgres-data: {}

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./config/psql_init.sql:/docker-entrypoint-initdb.d/psql_init.sql
    env_file:
      - ./.envs/.postgres
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: ./compose/bot/Dockerfile
    image: nn_bot
    depends_on:
      - postgres
    volumes:
      - .:/bot





