version: '3.8'

volumes:
  postgres-data: {}

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./psql_init.sql:/docker-entrypoint-initdb.d/psql_init.sql
    env_file:
      - .env
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
